### ISSUE TITLE
NaN/null deserialized to 0

### ISSUE THREAD

**Issue by flqw** [Litote/kmongo#95] opened 2018-11-26 14:24 UTC
Hi,

i've got an issue where i have a document containing an integer field set to NaN/null in mongo. The JacksonCodec used however deserializes the NaN/null values to 0 instead of null, bugging my business logic. The field in the respective entity class is an ``Int?``. Is this a bug or somehow configurable with the codec?

Thanks!

**Comment by zigzago** [comment] 2018-11-26 21:17
I do not reproduce the bug as you can see is this test: https://github.com/Litote/kmongo/commit/c88d36f883a12202e67ec9519a2a799fd422f0fb
Please provide a reproducible test case.

**Comment by flqw** [comment] 2018-11-26 23:41
This should do it

```
@Test
fun generateNaNInt() {
    col.updateOne("{}", "{$set:{int:NaN}}", UpdateOptions().upsert(true))      
    assertNull(col.findOne()!!.int)
    assertNull(col.withDocumentClass<Document>().findOne()!!["int"])
}
```

**Comment by zigzago** [comment] 2018-11-27 21:02
This is an interesting corner case. In java, there is no NaN value for the primitive int type. But NaN exists for float or double. 

When parsing the NaN value, bson4jackson (that KMongo uses under the hood) is getting a NaN Double, and then cast the double to an int (see https://github.com/michel-kraemer/bson4jackson/blob/master/src/main/java/de/undercouch/bson4jackson/BsonParser.java#L745 for the bson4jackson code)

And Double.NaN.toInt() is equals to 0 in java. This is the cause of the issue.

I think you have three options:

1) Change your mapping type from Int? to Double?
2) Open an issue in bson4jackson project
3) Write a custom Jackson deserializer for the class that contains the Int? field

This is definitely not a bug in KMongo. I close the issue.

HTH

**Closed by zigzago** 2018-11-27 21:02 UTC
