### ISSUE TITLE
Null or empty filter BSON passed to deleteMany causes "$and/$or/$nor must be a nonempty array"

### ISSUE THREAD

**Issue by jonpeterson** [Litote/kmongo#69] opened 2018-07-02 01:58 UTC
Passing either null or an empty filter BSON to `MongoCollection<T>.deleteMany` causes:

```
$and/$or/$nor must be a nonempty array
com.mongodb.MongoWriteException: $and/$or/$nor must be a nonempty array
	at com.mongodb.async.client.MongoCollectionImpl$9.onResult(MongoCollectionImpl.java:988)
	at com.mongodb.async.client.MongoCollectionImpl$9.onResult(MongoCollectionImpl.java:975)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
	at com.mongodb.async.client.AsyncOperationExecutorImpl$2$1.onResult(AsyncOperationExecutorImpl.java:105)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
...
```

https://github.com/Litote/kmongo/blob/9c65c81fdf0d860fe7003722ab6a6d52ddc9ac16/kmongo-coroutine-core/src/main/kotlin/org/litote/kmongo/coroutine/mongocollection.kt#L348-L351

**Comment by zigzago** [comment] 2018-07-02 19:38
Thanks for reporting. The issue is fixed in 3.8.1-SNAPSHOT and will be in 3.8.1 in two weeks.

**Closed** 2018-07-02 19:38 UTC
